# Generated by Django 3.2.6 on 2021-08-13 17:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0003_auto_20210813_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='size',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=8), default=[], size=8),
        ),
    ]
